#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_charybdis_4x6(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_QUOT, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_RSFT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RCTL, KC_LGUI, LT(1,KC_NO), KC_LALT, KC_BSPC, LT(1,KC_NO), KC_SPC, KC_ENT, KC_ENT),
	[1] = LAYOUT_charybdis_4x6(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_GRV, KC_BTN4, KC_BTN2, KC_UP, KC_BTN1, KC_LBRC, KC_RBRC, KC_BTN1, KC_BTN3, KC_BTN2, KC_TRNS, KC_EQL, KC_TRNS, KC_BTN3, KC_LEFT, KC_DOWN, KC_RGHT, DRGSCRL, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_BSLS, KC_TRNS, KC_TRNS, KC_BTN5, KC_PGDN, KC_DOT, KC_PGUP, KC_HOME, KC_END, KC_LALT, KC_SPC, DPI_MOD, S_D_MOD, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_DEL, SNP_TOG, KC_ENT, LT(2,KC_NO), LT(2,KC_NO)),
	[2] = LAYOUT_charybdis_4x6(KC_NO, KC_NO, KC_NO, RGB_M_B, RGB_M_P, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, EE_CLR, KC_CAPS, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, RGB_MOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_TRNS, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, RGB_RMOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, QK_BOOT, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO)
};

typedef union {
  uint32_t raw;
  struct {
    bool     rgb_layer_change :1;
  };
} user_config_t;

user_config_t user_config;

#define LAYER_0 0 // Base layer 0 for work / productivity
#define LAYER_1 1 // Base layer 1 for work / productivity
#define LAYER_2 2 // Base layer 2 for work / productivity
#define LAYER_3 3 // PAT || RTS focused base layer 0
#define LAYER_4 4 // PAT || RTS focused layer 1
#define LAYER_5 5 // PAT || RTS focused layer 2

#define LAYERS_EFFECT_SPEEDS ((uint8_t[]){ 64, 148, 255})

void keyboard_post_init_user(void) {
  // Call the keymap level matrix init.

  // Read the user config from EEPROM
  user_config.raw = eeconfig_read_user();

  // Set default layer, if enabled
  if (user_config.rgb_layer_change) {
    rgblight_enable_noeeprom();
    rgblight_sethsv_noeeprom(HSV_CYAN);
    rgblight_mode_noeeprom(RGB_MATRIX_BREATHING);
    rgb_matrix_set_speed_noeeprom(LAYERS_EFFECT_SPEEDS[0]);
  }
}

layer_state_t layer_state_set_user(layer_state_t state) {
    const uint32_t curr_layer = get_highest_layer(state);

    switch (curr_layer) {
    case LAYER_0 ... LAYER_2:
        if (user_config.rgb_layer_change) {
            rgblight_sethsv_noeeprom(HSV_CYAN);
            rgb_matrix_set_speed_noeeprom(LAYERS_EFFECT_SPEEDS[curr_layer % 3]);
        };
        break;
    case LAYER_3 ... LAYER_5:
        if (user_config.rgb_layer_change) {
            rgblight_sethsv_noeeprom(HSV_GREEN);
            rgb_matrix_set_speed_noeeprom(LAYERS_EFFECT_SPEEDS[curr_layer % 3]);
        }
        break;
    default: //  for any other layers, or the default layer
        if (user_config.rgb_layer_change) {
            rgblight_sethsv_noeeprom(HSV_CYAN);
            rgblight_mode_noeeprom(RGB_MATRIX_BREATHING);
            rgb_matrix_set_speed_noeeprom(LAYERS_EFFECT_SPEEDS[0]);
        }
        break;
    }
  return state;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case RGB_MODE_FORWARD ... RGB_MODE_GRADIENT: // For any of the RGB codes (see quantum_keycodes.h, L400 for reference)
        if (record->event.pressed) { //This disables layer indication, as it's assumed that if you're changing this ... you want that disabled
            if (user_config.rgb_layer_change) {        // only if this is enabled
                user_config.rgb_layer_change = false;  // disable it, and
                eeconfig_update_user(user_config.raw); // write the setings to EEPROM
            }
        }
        return true; break;
    default:
      return true; // Process all other keycodes normally
  }
}

void eeconfig_init_user(void) {  // EEPROM is getting reset!
  user_config.raw = 0;
  user_config.rgb_layer_change = true; // We want this enabled by default
  eeconfig_update_user(user_config.raw); // Write default value to EEPROM now

  // use the non noeeprom versions, to write these values to EEPROM too
  rgblight_enable(); // Enable RGB by default
  rgblight_sethsv(HSV_CYAN);  // Set it to CYAN by default
  rgblight_mode(RGB_MATRIX_BREATHING); // set to solid by default
  rgb_matrix_set_speed_noeeprom(LAYERS_EFFECT_SPEEDS[0]);
}
